Shark/urls.py
from django.contrib import admin
from django.urls import path
from lessons import loginviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', loginviews.home, name='home'),
    path('sign_up/', loginviews.sign_up, name='sign_up'),
    path('log_in/', loginviews.log_in, name='log_in')

]

msms/urls.py
from django.contrib import admin
from django.urls import path,include
from lessons import views
from lessons import Urls

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('lessons/student/', include('lessons.Urls.studentUrls')),
    path('lessons/admin/', include('lessons.Urls.adminUrls')),
    path('lessons/director/', include('lessons.Urls.directorUrls')),
    path('signpage/', include('lessons.Urls.loginUrls')),
]

lessons/models.py
from django.db import models
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import admin
from django import forms
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.contrib.auth.models import UserManager
import uuid 
import random


#helper file 
from lessons import helpers 
from django.utils.translation import gettext_lazy as _

LESSON_DURATION_MAX_LENGTH=10
LESSON_INTERVAL_MAX_LENGTH=22

def random_id():
    return str(random.randint(1111,9999))
#The User model 
class User(AbstractUser):
    USER_ROLES = (
        ('A', 'Administrator'),
        ('D', 'Director'),
        ('S', 'Student'),
    )

    role = models.CharField(max_length=1, blank=False, choices=USER_ROLES )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=20)
    email = models.EmailField(max_length=100,null=False, verbose_name="user name or email address", unique=True)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']
   
    def __str__(self):
        return '{}'.format(self.get_full_name())

#Student class 
class Student(models.Model):
    #unique student_id 
    id = models.AutoField(primary_key=True)
    #unique 4 digit student reference number
    reference_number =models.CharField(default = random_id, max_length=4, null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    nick_name = models.CharField(max_length=500, null=True)
    age = models.IntegerField(null=False)
    objects = models.Manager()
    dependent_id = models.IntegerField(null=True)
    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['reference_number'], name='unique_migration_refno_combination'
    #         )
    # ]


    def __str__(self):
        return (self.user.first_name + " " + self.user.last_name + " ID ("  + str(self.id) + ")" + "reference_number = " + self.reference_number)  
    


#Admin class
class Administrator(models.Model):
    #unique admin id 
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

#Director class 
class Director(models.Model):
    #unique admin id 
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.CharField( max_length=30, null=True)
    CHOICE_TITLE = ((1, "MRS") , (2, "MR") , (3,"MISS") , (4,"MS"))

    CHOICE_LESSON_DURATION = (
        (3, 60),
        (1, 30),
        (2, 45),
    )
    reference_number = models.CharField(max_length=50, null=False)
    title = models.IntegerField(choices=CHOICE_TITLE,default=1,blank=False)
    name = models.CharField(max_length=50, null=True)
    speciality = models.CharField(max_length=10, null=True)
    objects = models.Manager()
    



class Payment(models.Model):
    customer_id = models.IntegerField()
    staff_id = models.IntegerField()
    amount = models.FloatField(null=False)
    payment_date = models.DateTimeField(null=False)
    payment_type = models.IntegerField( null=False)
    create_time = models.DateTimeField(null=False)
    update_time = models.DateTimeField(null=False)


class Sys_user(models.Model):
    """User account"""
    # INSERT INTO `sys_user`(`id`, `username`, `password`, `salt`, `name`, `create_time`, `create_by`, `update_time`,
    # `update_by`) VALUES(1, 'admin', 'admin', '123456', 'super administrator', DEFAULT, NULL, DEFAULT, NULL)
    user_name = models.CharField(max_length=20, null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    password = models.CharField(max_length=20, null=True)
    salt = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=50, null=True)
    create_time = models.DateTimeField(null=False)
    update_time = models.DateTimeField(null=False)

class Sys_authority(models.Model):
    """Role Table"""
    label = models.CharField(max_length=20, null=True, verbose_name="Role Name")
    alias = models.CharField(max_length=20, null=True, verbose_name="Role Alias")
    sort = models.IntegerField( null=False, verbose_name="sort", default=0)
    create_time = models.DateTimeField(null=False)
    update_time = models.DateTimeField(null=False)


class Sys_user_authority(models.Model):
    """User Role Table"""
    user_id = models.IntegerField()
    authority_id = models.IntegerField()
    create_time = models.DateTimeField(null=False)
    update_time = models.DateTimeField(null=False)

class Lesson(models.Model):
    name = models.CharField(max_length=50, null=True)
    lesson_price = models.FloatField()
    duration = models.IntegerField()
    description = models.CharField(max_length=500, null=True)
    objects = models.Manager()

    CHOICE_LESSON_DURATION = (
        (3, 60),
        (1, 30),
        (2, 45),
    )



class LessonRequest(models.Model):
    
    REQUEST_BOOK_STATUS_CHOICES = (
        ('P', 'Pending'),
        ('R', 'Rejected'),
        ('A', 'Accepted'),
        ('O', 'Old'),
    )

    student_id = models.ForeignKey(to=Student, related_name = 'request', on_delete=models.CASCADE )
    book_status = models.CharField(max_length=1, blank=False, choices=REQUEST_BOOK_STATUS_CHOICES,default= "P" )
    lesson_time = models.TimeField( null=False)
    lesson_interval = models.IntegerField(blank=False,choices=helpers.CHOICE_LESSON_INTERVAL, default=1 )
    lesson_duration = models.IntegerField(blank=False, choices=helpers.CHOICE_LESSON_DURATION, default=1)
    number_of_lessons = models.IntegerField(validators=[helpers.validateLessonNumber])
    submit_depend_id = models.ForeignKey(to=Student, related_name='request_commit', on_delete=models.CASCADE)
    lesson_teacher = models.ForeignKey(to=Teacher, related_name = 'Teaching', on_delete=models.CASCADE )
    lesson_type = models.ForeignKey(to=Lesson, related_name = 'Lessontype', on_delete=models.CASCADE )
    lesson_start_date = models.DateField(null=True,default = now)
    date_created = models.DateField(null=False,default = now)
    remarks = models.CharField(max_length=500, null=True)
    lesson_day_of_week = models.IntegerField(blank = False , choices=helpers.CHOICE_DAY_OF_THE_WEEK )
    objects = models.Manager()

    def isFulfilled(self):
        if self.book_status=='A':
            return True
    def isRejected(self):
        if self.book_status=="R":
            return True 
      

    @property
    def getStudentName(self):
        obj = self.student_id
        user = obj.user
        return str(user)
        
        
        # .first_name.removeprefix('"')
        # return  ( first_name, " " , obj.user.last_name)
         

    # for epic 2
    #additionalInfo = models.TextField(default = "N/A")
    

class Term(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, null = False)
    start_of_term_date = models.DateField(null=False,default = now)
    end_of_term_date =  models.DateField(null=False,default = now)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager() 
    def __str__(self):
        return self.name 




    
class LessonBooking(models.Model):
    id = models.AutoField(primary_key=True)
    request = models.ForeignKey(to=LessonRequest , related_name = 'LessonBookings', on_delete=models.CASCADE )
    #lesson_id = models.IntegerField(max_length=20)
    teacher_id = models.IntegerField(null=False, default=1)
    lesson_time = models.TimeField(null=False)
    finish_time = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    lesson_start_date = models.DateField(validators=[helpers.validateDate]) 
    lesson_end_date = models.DateField(validators=[helpers.validateDate]) 
    CHOICE_LESSON_DURATION = (
        (3, 60),
        (1, 30),
        (2, 45),
    )
    CHOICE_LESSON_INTERVAL = ((1, '1 lesson every week'), (2, '1 lesson every 2 weeks'))
    lesson_duration = models.IntegerField(choices=CHOICE_LESSON_DURATION,default=1,blank=False)
    lesson_interval = models.IntegerField(choices=CHOICE_LESSON_INTERVAL,default=1,blank=False)
    lesson_type = models.CharField(max_length=50, null=True)
    number_of_lessons = models.IntegerField(validators=[helpers.validateLessonNumber])
    lesson_day_of_week = models.IntegerField(blank = False , choices=helpers.CHOICE_DAY_OF_THE_WEEK )
    lesson_teacher = models.CharField(max_length = 20, default='')
    objects = models.Manager()

lessons/views/directorViews.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.utils.timezone import now

from ..forms import directorForms
from lessons.models import User as database
from lessons import models
from lessons.forms import directorForms
from django.contrib.auth.decorators import login_required


@login_required
def directorHomePage(request,Logged_ID):

   # obj =  database.objects.filter(Student = "testbob")
    
    data ={
        'name' : database.objects.get(id =Logged_ID).first_name,
        'Logged_ID' : Logged_ID,
        'value' : 0,
        'database':database.objects.filter()
    }


    return render(request,'directorHome.html',data)


@login_required
def FormRender( request,Logged_ID,my_id,inputdatabase,formtype):
    alert = ""
    if (my_id == 0):
        form = formtype(request.POST or None)
    else:
        obj =  get_object_or_404(inputdatabase,id =my_id)
        form = formtype(request.POST or None, instance =obj)
    if form.is_valid():
        if("Edit" in request.POST):
            form.save()
            alert = "form saved"
        elif("Delete" in request.POST):
            instance = inputdatabase.objects.get(id=my_id)
            instance.delete()
            return HttpResponseRedirect(reverse('directorHome' , args =(Logged_ID,)) )
        elif("Create" in request.POST):
            form.save()
            return HttpResponseRedirect(reverse('directorHome' , args =(Logged_ID,)) )
    data ={
        "form" : form,
        'Logged_ID' : Logged_ID,
        'my_id' : my_id,
        "alert":alert
    }


    return render(request,'directorDataChange.html',data)


@login_required
def ShowRender( request,Logged_ID,inputdatabase,pagetype,url):

    data ={
        "URL" :url,
        "text" : pagetype,
        'Logged_ID' : Logged_ID,
        "database":inputdatabase.objects.filter(),
        "value":0
    }
    return render(request,'directorSeeData.html',data)



@login_required
def UserFormPage(request,Logged_ID,my_id):


    return(FormRender( request,Logged_ID,my_id,models.User,directorForms.Userform))

@login_required
def StudentFormPage(request,Logged_ID,my_id):


    return(FormRender( request,Logged_ID,my_id,models.Student,directorForms.Studentform))


@login_required
def DirectorFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Director,directorForms.Directorform))


@login_required
def TeacherFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Teacher,directorForms.Teacherform))


@login_required
def PaymentFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Payment,directorForms.Paymentform))


@login_required
def Sys_userFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Sys_user,directorForms.Sys_user_form))


@login_required
def Sys_authorityFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Sys_authority,directorForms.Sys_authority_form))


@login_required
def Sys_user_authorityFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Sys_user_authority,directorForms. Sys_user_authority_form))


@login_required
def LessonFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.Lesson,directorForms.Lessonsform))


@login_required
def LessonRequestFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.LessonRequest,directorForms.LessonRequestform))


@login_required
def LessonBookingFormPage(request,Logged_ID,my_id):

    return(FormRender( request,Logged_ID,my_id,models.LessonBooking,directorForms.LessonBookingform))








@login_required
def UserShowPage(request,Logged_ID,):


    return(ShowRender( request,Logged_ID,models.User,"user",'UserFormPage'))



@login_required
def StudentShowPage(request,Logged_ID,):


    return(ShowRender( request,Logged_ID,models.Student,"student",'StudentFormPage'))


@login_required
def DirectorShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Director,"Director",'DirectorFormPage'))


@login_required
def TeacherShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Teacher,"Teacher",'TeacherFormPage'))


@login_required
def PaymentShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Payment,"Payment",'PaymentFormPage'))


@login_required
def Sys_userShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Sys_user,"Sys_user",'Sys_userFormPage'))


@login_required
def Sys_authorityShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Sys_authority,"Authorities",'Sys_authorityFormPage'))


@login_required
def Sys_user_authorityShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Sys_user_authority,"UserAuthorities",'Sys_user_authorityFormPage'))


@login_required
def LessonShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.Lesson,"lessons",'LessonFormPage'))


@login_required
def LessonRequestShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.LessonRequest,"lesson Requests",'LessonRequestFormPage'))


@login_required
def LessonBookingShowPage(request,Logged_ID,):

    return(ShowRender( request,Logged_ID,models.LessonBooking,"lesson booked",'LessonBookingFormPage'))

lessons/views/home.py
from django.shortcuts import render
from django.http import HttpResponse
#default view 
def home(request):
    return render(request,'home.html')

lessons/views/loginviews.py
from django.shortcuts import render,redirect
from ..forms.loginforms import LogInForm,SignUpForm
from django.contrib.auth import authenticate,login
from django.contrib import messages


def home(request):
 user=request.user
 return render(request, 'home.html',{'user:user'})

def sign_up(request):
 if request.method =='POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
        user=form.save()
        login(request, user)
        return redirect('log_in')
 else:
     form=SignUpForm()
    # return render(request, 'home.html')
 return render(request, 'sign_up.html', {'form': form})


def student_home(request):
    return render(request, 'student_home.html')

def log_in(request):
    if request.method =='POST':
       form = LogInForm(request.POST)
       if form.is_valid():
           # form.save()
           username = form.cleaned_data.get('username')
           password = form.cleaned_data.get('password')
           user = authenticate(username=username, password=password)
           print(user)
           if user is not None:
               login(request, user)
               return redirect('student_home')
       messages.add_message(request,messages.ERROR,"Invalid")
    form=LogInForm()
    return render(request, 'log_in.html', {'form': form})

lessons/templates/adminAddBooking.html
 {% extends 'adminBase.html' %}
 {% block body %}
    <h3 class="text-center m-4">Add Booking</h3>
    {% if success %}
        <div class="alert alert-success" role="alert">
            The booking was made successfully
            <a href="{% url 'home' %}" class="alert-link"> Return to Home Page</a>
        </div>
    {% else %}
        <div class="row-justify-content-center">
            <div class="col-6">
                <div class="card bg-light mb-3">
                    <div class="card-header">Booking Details</div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% comment %} {% include 'bootstrap_form.html' with form=form %} {% endcomment %}
                            {{ form.as_p }}
                            <button type="submit" name = "CustomBook" value = "Submit" class="btn btn-primary">Book By Requested Start Date</button>
                            <button type="submit" name = "DefaultBook" value = "Submit" class="btn btn-primary">Default Book For Term</button>
                            <input type="submit" value="Reject" name = "Reject"  class="btn btn-primary">
                            <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
                        </form>
                    </div>
                  </div>
            </div>

        </div>
    {% endif %}
 
 {% endblock body %}

lessons/templates/adminAddTermDates.html
{% extends 'adminBase.html' %}
{% block body %}
   <h3 class="text-center m-4">Add Term</h3>
   {% if success %}
       <div class="alert alert-success" role="alert">
           The term was made successfully
           <a href="{% url 'home' %}" class="alert-link"> Return to Home Page</a>
       </div>
   {% else %}
       <div class="row-justify-content-center">
           <div class="col-6">
               <div class="card bg-light mb-3">
                   <div class="card-header">Header</div>
                   <div class="card-body">
                       <form action="" method="POST">
                           {% csrf_token %}
                           {% comment %} {% include 'bootstrap_form.html' with form=form %} {% endcomment %}
                           {{ form.as_p }}
                           <button type="submit" name = "Submit" value = "Submit" class="btn btn-primary">Add Term</button>
                           <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
                       </form>
                   </div>
                 </div>
           </div>

       </div>
   {% endif %}

{% endblock body %}

lessons/templates/adminEditBooking.html
{% extends 'adminBase.html' %}
{% block body %}
   <h3 class="text-center m-4">Add Booking</h3>
   {% if success %}
       <div class="alert alert-success" role="alert">
           The booking was made successfully
           <a href="{% url 'home' %}" class="alert-link"> Return to Home Page</a>
       </div>
   {% else %}
       <div class="row-justify-content-center">
           <div class="col-6">
               <div class="card bg-light mb-3">
                   <div class="card-header">Header</div>
                   <div class="card-body">
                       <form action="{% url 'editBookingRecord' id=data.id %}" method="POST">
                           {% csrf_token %}
                           {% comment %} {% include 'bootstrap_form.html' with form=form %} {% endcomment %}
                           {{ form.as_p }}
                           <button type="submit" name = "Update" value = "Submit" class="btn btn-primary">Update & Book By Requested Start Date</button>
                            <button type="submit" name = "Delete"  class="btn btn-primary">Delete Booking</button>
                         
                           <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
                       </form>
                   </div>
                 </div>
           </div>

       </div>
   {% endif %}

{% endblock body %}

lessons/templates/adminEditTermDates.html
{% extends 'adminBase.html' %}
{% block body %}
   <h3 class="text-center m-4">Add Booking</h3>
   {% if success %}
       <div class="alert alert-success" role="alert">
           The term was created successfully
           <a href="{% url 'home' %}" class="alert-link"> Return to Home Page</a>
       </div>
   {% else %}
       <div class="row-justify-content-center">
           <div class="col-6">
               <div class="card bg-light mb-3">
                   <div class="card-header">Header</div>
                   <div class="card-body">
                       <form action="" method="POST">
                           {% csrf_token %}
                           {% comment %} {% include 'bootstrap_form.html' with form=form %} {% endcomment %}
                           {{ form.as_p }}
                           <button type="submit" name = "Update"  class="btn btn-primary">Update</button>
                           <button type="submit" name = "Delete"  class="btn btn-primary">Delete Term</button>
                         
                           <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
                       </form>
                   </div>
                 </div>
           </div>

       </div>
   {% endif %}

{% endblock body %}

lessons/templates/adminViewRequests.html
{% extends 'adminBase.html' %}
{% block body  %}
          <h3 class="m-4">All Requests</h3>
          <div class="row">
              <div class="col-12">
                {% if requests %}
                    <div class="card bg-light mb-4 ms-4 me-4" >
                        <div class="card-header">Requests</div>
                        <div class="card-body">
                            <div class ="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                      <tr>
                                        <th scope="col">Date Sent</th>
                                        <th scope="col">Student</th>
                                        <th scope="col">Lesson Type</th>
                                        <th scope="col">book_status</th>
                                        <th scope="col">ACTIONS</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {% for request in requests %}
                                        <tr>
                                          <td>{{request.date_created}}</td>
                                          <td>{{request.student_id}}</td>
                                          <td>{{request.lesson_type}}</td>
                                          <td>{{request.get_book_status_display}}</td>
                                          <td>
                                            <button type="button" class="btn btn-success me-1" href="{% url 'view_request' request.id %}" data-bs-toggle="modal" 
                                            data-bs-target="#myModal{{request.id}}">View Request</button>
                                            <!-- Modal - View Request -->
                                            <div class="modal" role="dialog" id="myModal{{request.id}}"  tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
                                              <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title">Request from {{request.Student}}</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true"></span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <ul class="list-unstyled">
                                                        <li>Request book_status : <strong>{{request.get_book_status_display}}</strong> </li>
                                                        <li>Request Made On : <strong>{{request.date_created}}</strong> </li>
                                                        <li>Teacher : <strong>{{request.lesson_teacher}}</strong> </li>
                                                        <li>Lesson Duration : <strong>{{request.get_lesson_duration_display}}</strong> </li>
                                                        <li>Time Of Lesson : <strong>{{request.lesson_time|time:"H:i:s"}}</strong> </li>
                                                        <li>Lesson Type : <strong>{{request.lesson_type}}</strong> </li>
                                                        <li>Student Name : <strong>{{request.getStudentName}}</strong> </li>
                            
                                                    </ul>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-btn-primary" data-bs-dismiss="modal">Close</button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>

                                            
                                            {% if not request.isRejected %}
                                            {% if request.isFulfilled %}
                                            <!--IF REQUEST IS FULFILLED SHOULD HAVE OPTION TO EDIT/DELETE BOOKING-->
                                                <a class="btn btn-success me-1" href="{% url 'edit_booking' request.id  %}">Edit Booking</a>
                                                <a class="btn btn-success me-1" href="{% url 'viewLessonSchedule' request.id  %}">View Schedule</a>
                                            <!--IF REQUEST IS UNFULFILLED, ENABLE BUTTON TO BOOK REQUEST-->
                                            {% else%}
                                              <a class="btn btn-warning me-1" href="{% url 'add_booking' request.id  %}">Fulfil Request</a>
                                            {% endif %}
                                            {% endif %}
                                          </td>
                                        </tr>
                                      {% endfor %}
                                    </tbody>
                                  </table>
                            </div>

                        </div>
                    </div>
                {% else %}
                    <h5 class="alert alert-primary ms-4 me-4">No Requests</h5>
                {% endif %}
                  
              </div>
          </div>

{% endblock body %}

lessons/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <title>Music Management System</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
    <!--Keep scripts at bottom-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

lessons/templates/viewLessonSchedule.html
{%extends "base.html"%}
{% block body %}
<h3 class="m-4">Schedule for {{request.getStudentName}} </h3>
<div class="row">
    <div class="col-12">
      {% if booking %}
          <div class="card bg-light mb-4 ms-4 me-4" >
              <div class="card-header">Booked Lessons</div>
              <div class="card-body">
                  <div class ="table-responsive">
                      <table class="table table-hover">
                          <thead>
                            <tr>
                              <th scope="col">Date</th>
                              <th scope="col">Day Of Week</th>
                              <th scope="col">Time Of Lesson</th>
                              <th scope="col">Lesson Type</th>
                              <th scope="col">Lesson Teacher</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for date in date_list %}
                              <tr>
                                <td>{{date}}</td>
                                <td>{{booking.get_lesson_day_of_week_display}}</td>
                                <td>{{booking.lesson_time|time:"H:i:s"}}</td>
                                <td>{{booking.lesson_type}}</td>
                                <td> {{booking.lesson_teacher}}  </td>
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                  </div>

              </div>
          </div>
      {% else %}
          <h5 class="alert alert-primary ms-4 me-4">No Requests</h5>
      {% endif %}
        
    </div>
</div>
{% endblock body %}